---
- name: "Deploy logging dependencies"
  hosts: "{{ cifmw_target_hook_host | default('localhost')  }}"
  gather_facts: false
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  tasks:
    - name: Deploy logging dependencies
      ansible.builtin.import_role:
        name: deploy-logging-dependencies
